[package]
name = "aoc_2015"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytelines = "2.4.0"
divisors = "0.2.1"
md5 = "0.7.0"
rayon = "1.5.3"
regex = "1.6.0"
serde_json = "1.0.85"